//obtener todos los usuarios
GET http://localhost:3000/api/usuarios

### // obtener un usuario por su id
GET http://localhost:3000/api/usuarios/1
### // registrar nuevo usuario

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "Carmen",
    "apellidos": "Garcia",
    "email": "car@gmail.com",
    "password": "12345",
    "username": "Carmen777"
}


###

PUT http://localhost:3000/api/usuarios

### //borrar usuario por id

DELETE http://localhost:3000/api/usuarios/6

###

GET http://localhost:3000/api/recetas